/**
 * manifest.ts — Central list of all registered tool names.
 * Used by Curator to initialize fluent methods without loading full tool handlers.
 */
export const TOOL_NAMES = [
    'ask_llm',

    'process_feed',
    'classify',
    'classify_et',
    'feature_extraction',
    'upsert_resource',
    'upsert_text',
    'upsert_relation',
    'query_resources',
    'fetch_html',
    'scrape_resource',
    'extract_resource_links',
    'execute_script',
    'classify_udc',
    'udc_cat',
    'iterate',
    'debug',
    'set_context',
    'get_context',
    'get_resource',
    'delete_resource',
    'extract_udc_hierarchy',
    'format_list',
    'select_objects',
    'evaluate_condition',
    'regex_replace',
    'web_search',
    'browser_action',
    'llama_health',
    'llama_request',
    'llama_models',
    'llama_chat_completion',
    'llama_completion',
    'llama_tokenize',
    'llama_detokenize',
    'llama_apply_template',
    'llama_embedding',
    'llama_v1_embeddings',
    'llama_rerank',
    'llama_props_get',
    'llama_props_set',
    'llama_slots',
    'llama_slot_action',
    'llama_metrics',
    'llama_lora_list',
    'llama_lora_set',
    'llama_responses',
    'llama_messages',
    'llama_messages_count_tokens',
    'internal:trigger_agent'





] as const;

export type ToolName = typeof TOOL_NAMES[number];

/**
 * Convenience constant mapping for IDE autocompletion (Enum-style).
 */
export const TOOLS = {
    ASK_LLM: 'ask_llm',
    PROCESS_FEED: 'process_feed',
    CLASSIFY: 'classify',
    CLASSIFY_ET: 'classify_et',
    FEATURE_EXTRACTION: 'feature_extraction',
    UPSERT_RESOURCE: 'upsert_resource',
    UPSERT_TEXT: 'upsert_text',
    UPSERT_RELATION: 'upsert_relation',
    QUERY_RESOURCES: 'query_resources',
    FETCH_HTML: 'fetch_html',
    SCRAPE_RESOURCE: 'scrape_resource',
    EXTRACT_RESOURCE_LINKS: 'extract_resource_links',
    EXECUTE_SCRIPT: 'execute_script',
    CLASSIFY_UDC: 'classify_udc',
    UDC_CAT: 'udc_cat',
    ITERATE: 'iterate',
    DEBUG: 'debug',
    SET_CONTEXT: 'set_context',
    GET_CONTEXT: 'get_context',
    GET_RESOURCE: 'get_resource',
    DELETE_RESOURCE: 'delete_resource',
    EXTRACT_UDC_HIERARCHY: 'extract_udc_hierarchy',
    FORMAT_LIST: 'format_list',
    SELECT_OBJECTS: 'select_objects',
    EVALUATE_CONDITION: 'evaluate_condition',
    REGEX_REPLACE: 'regex_replace',
    WEB_SEARCH: 'web_search',
    BROWSER_ACTION: 'browser_action',
    LLAMA_HEALTH: 'llama_health',
    LLAMA_REQUEST: 'llama_request',
    LLAMA_MODELS: 'llama_models',
    LLAMA_CHAT_COMPLETION: 'llama_chat_completion',
    LLAMA_COMPLETION: 'llama_completion',
    LLAMA_TOKENIZE: 'llama_tokenize',
    LLAMA_DETOKENIZE: 'llama_detokenize',
    LLAMA_APPLY_TEMPLATE: 'llama_apply_template',
    LLAMA_EMBEDDING: 'llama_embedding',
    LLAMA_V1_EMBEDDINGS: 'llama_v1_embeddings',
    LLAMA_RERANK: 'llama_rerank',
    LLAMA_PROPS_GET: 'llama_props_get',
    LLAMA_PROPS_SET: 'llama_props_set',
    LLAMA_SLOTS: 'llama_slots',
    LLAMA_SLOT_ACTION: 'llama_slot_action',
    LLAMA_METRICS: 'llama_metrics',
    LLAMA_LORA_LIST: 'llama_lora_list',
    LLAMA_LORA_SET: 'llama_lora_set',
    LLAMA_RESPONSES: 'llama_responses',
    LLAMA_MESSAGES: 'llama_messages',
    LLAMA_MESSAGES_COUNT_TOKENS: 'llama_messages_count_tokens',
    TRIGGER_AGENT: 'internal:trigger_agent'
} as const;
