export const keerisDomainPlugin = {
  name: 'keeris-domain',
  scripts: {
    'keeris.search': async ({ query }) => ({ query }),
  },
  agents: {
    vikerraadio_kauamangiv_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: '1037846', programTitle: 'Kauamängiv', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    vikerraadio_originaal_ja_koopia_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: '1037950', programTitle: 'Originaal ja koopia', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    vikerraadio_kantri_alati_jaab_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: '1037843', programTitle: 'Kantri alati jääb', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    vikerraadio_heldur_karmo_aeg_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: '1610049724', programTitle: 'Heldur Karmo aeg', refresh: false, isFinal: true },
      schedule: '0 0 1 1 *',
      enabled: false,
    },
    vikerraadio_kuldrandevuu_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: '1037864', programTitle: 'Kuldrandevüü', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    vikerraadio_muusika_noudlikule_maitsele_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: '1608635380', programTitle: 'Muusika nõudlikule maitsele', refresh: false },
      schedule: '0 0 1 1 *',
      enabled: false,
    },
    klassikaraadio_fantaasia_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: '1038126', programTitle: 'Fantaasia', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    klassikaraadio_lihtsalt_nostalgia_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: 'https://klassikaraadio.err.ee/1610109911/lihtsalt-nostalgia-kaisa-johvik', programTitle: 'Lihtsalt nostalgia', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    vikerraadio_oomuusika_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: 'https://vikerraadio.err.ee/1610113264/oomuusika', programTitle: 'Öömuusika', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    klassikaraadio_helitrakk_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: 'https://klassikaraadio.err.ee/1610105843/helitrakk', programTitle: 'Heliträkk', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    klassikaraadio_kella_6_dzass_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: '1038156', programTitle: 'Kella-6-džäss', refresh: false },
      schedule: '0 * * * *',
      enabled: false,
    },
    vikerraadio_jaak_joala_parimad_laulud_scrape: {
      type: 'Curator_Tool',
      toolName: 'vikerraadio_scrape',
      args: { seriesContentId: 'https://vikerraadio.err.ee/1609719716/jaak-joala-parimad-laulud', programTitle: 'Jaak Joala parimad laulud', refresh: false },
      schedule: '0 0 1 1 *',
      enabled: false,
    },
    keeris_kauamangiv_scrape: {
      type: 'Curator_Tool',
      toolName: 'keeris_scrape',
      args: { refresh: false },
      schedule: '* * * * *',
      enabled: true,
    },
  },
};