import YAML from 'yaml';

export interface GenerateOptions {
  spec: string | Record<string, any>;
  namespace?: string;
  defaultBaseUrl?: string;
}

export interface GeneratedToolResult {
  code: string;
  operationsCount: number;
}

function sanitizeIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^_+|_+$/g, '');
}

function toCamelCase(str: string): string {
  return str.replace(/[-_]([a-z0-9])/gi, (_, c) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

export function generateStaticOpenApiTools(options: GenerateOptions): GeneratedToolResult {
  let doc: any;
  if (typeof options.spec === 'string') {
    const trimmed = options.spec.trim();
    if (trimmed.startsWith('{')) {
      doc = JSON.parse(trimmed);
    } else {
      doc = YAML.parse(trimmed);
    }
  } else {
    doc = options.spec;
  }

  const namespace = options.namespace || sanitizeIdentifier(doc.info?.title || 'api').toLowerCase();
  const servers = doc.servers || [];
  const defaultBaseUrl = options.defaultBaseUrl || servers[0]?.url || 'https://api.example.com';

  const paths = doc.paths || {};
  const operations: Array<{
    operationId: string;
    method: string;
    path: string;
    summary: string;
    description: string;
    parameters: any[];
    requestBody?: any;
    schema: Record<string, any>;
  }> = [];

  for (const [pathKey, pathItem] of Object.entries<any>(paths)) {
    const methods = ['get', 'post', 'put', 'delete', 'patch', 'options', 'head'];
    for (const method of methods) {
      if (!pathItem[method]) continue;
      const op = pathItem[method];
      const rawOpId = op.operationId || `${method}_${pathKey.replace(/[{}\/]/g, '_')}`;
      const operationId = sanitizeIdentifier(rawOpId);
      const summary = op.summary || `${method.toUpperCase()} ${pathKey}`;
      const description = op.description || summary;
      const parameters = [...(pathItem.parameters || []), ...(op.parameters || [])];
      const requestBody = op.requestBody;

      // Build JSON Schema for tool parameters
      const properties: Record<string, any> = {};
      const required: string[] = [];

      for (const p of parameters) {
        if (!p.name) continue;
        properties[p.name] = {
          type: p.schema?.type || 'string',
          description: p.description || `${p.in} parameter: ${p.name}`,
        };
        if (p.required) required.push(p.name);
      }

      if (requestBody?.content?.['application/json']?.schema) {
        const bodySchema = requestBody.content['application/json'].schema;
        properties['body'] = bodySchema;
        if (requestBody.required) required.push('body');
      }

      const schema = {
        type: 'object',
        properties,
        ...(required.length > 0 ? { required } : {}),
      };

      operations.push({
        operationId,
        method: method.toUpperCase(),
        path: pathKey,
        summary,
        description,
        parameters,
        requestBody,
        schema,
      });
    }
  }

  // Generate TypeScript code
  let ts = `// Auto-generated by @curator/plugin-openapi
// Namespace: ${namespace}
// Title: ${doc.info?.title || 'OpenAPI Specification'}
// Version: ${doc.info?.version || '1.0.0'}

export interface OpenApiPluginConfig {
  baseUrl?: string;
  headers?: Record<string, string>;
  fetchFn?: typeof fetch;
}

`;

  // Generate Tool interfaces
  for (const op of operations) {
    const typeName = `${toPascalCase(op.operationId)}Args`;
    ts += `export interface ${typeName} {\n`;
    for (const [propName, propDef] of Object.entries<any>(op.schema.properties)) {
      const isReq = op.schema.required?.includes(propName);
      const tsType = propName === 'body' ? 'any' : (propDef.type === 'integer' || propDef.type === 'number' ? 'number' : propDef.type === 'boolean' ? 'boolean' : 'string');
      ts += `  /** ${propDef.description || propName} */\n`;
      ts += `  ${propName}${isReq ? '' : '?'}: ${tsType};\n`;
    }
    ts += `}\n\n`;
  }

  // Generate Tool Definitions Factory
  ts += `export function create${toPascalCase(namespace)}Tools(config: OpenApiPluginConfig = {}) {\n`;
  ts += `  const baseUrl = (config.baseUrl || ${JSON.stringify(defaultBaseUrl)}).replace(/\\/+$/, '');\n`;
  ts += `  const customFetch = config.fetchFn || globalThis.fetch;\n\n`;
  ts += `  return {\n`;

  for (const op of operations) {
    const toolName = `${namespace}_${op.operationId}`;
    ts += `    ${op.operationId}: {\n`;
    ts += `      name: ${JSON.stringify(toolName)},\n`;
    ts += `      description: ${JSON.stringify(op.description)},\n`;
    ts += `      parameters: ${JSON.stringify(op.schema, null, 6)},\n`;
    ts += `      execute: async (args: any, context?: any) => {\n`;
    ts += `        let url = \`\${baseUrl}${op.path}\`;\n`;
    ts += `        const queryParams = new URLSearchParams();\n`;
    ts += `        const reqHeaders: Record<string, string> = { 'Accept': 'application/json', ...(config.headers || {}) };\n\n`;

    // Parameter mapping
    for (const p of op.parameters) {
      if (p.in === 'path') {
        ts += `        if (args.${p.name} !== undefined) url = url.replace('{${p.name}}', encodeURIComponent(String(args.${p.name})));\n`;
      } else if (p.in === 'query') {
        ts += `        if (args.${p.name} !== undefined) queryParams.set('${p.name}', String(args.${p.name}));\n`;
      } else if (p.in === 'header') {
        ts += `        if (args.${p.name} !== undefined) reqHeaders['${p.name}'] = String(args.${p.name});\n`;
      }
    }

    ts += `        const queryString = queryParams.toString();\n`;
    ts += `        if (queryString) url += \`?\${queryString}\`;\n\n`;

    if (['POST', 'PUT', 'PATCH'].includes(op.method)) {
      ts += `        let body: any = undefined;\n`;
      ts += `        if (args.body !== undefined) {\n`;
      ts += `          body = JSON.stringify(args.body);\n`;
      ts += `          reqHeaders['Content-Type'] = 'application/json';\n`;
      ts += `        }\n`;
      ts += `        const response = await customFetch(url, {\n`;
      ts += `          method: '${op.method}',\n`;
      ts += `          headers: reqHeaders,\n`;
      ts += `          body,\n`;
      ts += `        });\n`;
    } else {
      ts += `        const response = await customFetch(url, {\n`;
      ts += `          method: '${op.method}',\n`;
      ts += `          headers: reqHeaders,\n`;
      ts += `        });\n`;
    }

    ts += `        const text = await response.text();\n`;
    ts += `        let data: any;\n`;
    ts += `        try { data = JSON.parse(text); } catch { data = text; }\n`;
    ts += `        if (!response.ok) {\n`;
    ts += `          throw new Error(\`OpenAPI HTTP \${response.status} from \${url}: \${typeof data === 'string' ? data : JSON.stringify(data)}\`);\n`;
    ts += `        }\n`;
    ts += `        return data;\n`;
    ts += `      }\n`;
    ts += `    },\n`;
  }

  ts += `  };\n`;
  ts += `}\n\n`;

  // Generate Plugin wrapper
  ts += `export function ${toCamelCase(namespace)}Plugin(config: OpenApiPluginConfig = {}) {\n`;
  ts += `  const tools = create${toPascalCase(namespace)}Tools(config);\n`;
  ts += `  return {\n`;
  ts += `    name: ${JSON.stringify(namespace)},\n`;
  ts += `    version: '1.0.0',\n`;
  ts += `    description: ${JSON.stringify(doc.info?.description || `OpenAPI integration for ${namespace}`)},\n`;
  ts += `    tools,\n`;
  ts += `  };\n`;
  ts += `}\n`;

  return {
    code: ts,
    operationsCount: operations.length,
  };
}
