// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/12/2025, 02:00:46
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/joela/dev/curator/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/joela/dev/curator/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/joela/dev/curator/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/joela/dev/curator/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/joela/dev/curator/plugins/**/*.{js,ts,mjs}","C:/Users/joela/dev/curator/composables/**/*.{js,ts,mjs}","C:/Users/joela/dev/curator/utils/**/*.{js,ts,mjs}","C:/Users/joela/dev/curator/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/joela/dev/curator/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/joela/dev/curator/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;