services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    pull_policy: always
    container_name: llama-cpp-server
    ports:
      - "8080:8080"
    volumes:
      - ../curator-rust/assets/models:/models:ro
    command:
      - -m
      - /models/google_gemma-4-26B-A4B-it-Q4_K_M.gguf
      - -c
      - "2048"
      - -n
      - "256"
      - --host
      - 0.0.0.0
      - --port
      - "8080"
